inherit_from:
  - config/rubocop/rubocop.yml
  - config/rubocop/rails.yml
  - config/rubocop/rspec.yml



AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - vendor/**/* # rubocop config/default.yml
    - db/schema*.rb
    - db/migrate/**/*
    - bin/*
